### ISSUE TITLE
`salesorders` query: error when fetching positions

### ISSUE THREAD

**Issue by werner-freytag** [cobai/graphql-admin-api#3]
When I also query the `positions` when picking up the orders via `salesorders`, I get an error:

> Cannot return null for non-nullable type: 'null' within parent 'Salesorder' (/salesorders/edges[0]/node/positions)

Apparently the positions are not provided. With a single query via `salesorder(id)`, on the other hand, I can query the positions and get no error.

**Comment by DirkLachowski** [comment]
Internal reference: https://lab.cobai.io/cobai/online-sales-platform/issues/-/issues/514

**Comment by DirkLachowski** [comment]
Fixed, but not in production yet. Could you give it a try at `https://opc-dev2.cobai.io/graphql` (same credentials, only a different url)? 

Note: As soon as you query for any `positions` subfield (that is, any field in the selection set path `edges/node/positions/**`), we for now enforce an upper limit of `20` for the page size until we better understand implications of bigger result sets. We can adjust that limit if your use case requires a bigger one.

**Comment by werner-freytag** [comment]
Thanks, works with the dev2 endpoint. A limit of 20 is absolutely suitable for my needs.

**Comment by DirkLachowski** [comment]
Thanks for the update. Will be on prod from next Monday.
