### ISSUE TITLE
Suggestion: Unify spelling of mail/email

### ISSUE THREAD

**Issue by werner-freytag** [cobai/graphql-admin-api#5]
Just another suggestion: 

In the `Contact` type you use `email` while the field in the `Address` type is named `mail`. I guess it's better to unify the spelling as long as the API is Beta.

**Comment by DirkLachowski** [comment]
Ref: https://lab.cobai.io/cobai/online-sales-platform/issues/-/issues/520

**Comment by DirkLachowski** [comment]
`mail` is now deprecated and replaced by `email` in the `Address` type. Changelog:  https://www.cobai.com/docs/store-admin-gql/api-changes
